<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Media\Icons\FitImage.png" />
    <None Remove="Media\Icons\PanHand.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.WPF" Version="5.1.59" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Media\Icons\FitImage.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Media\Icons\PanHand.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
